"""Enumerations for the DebateEngine schema system."""

from __future__ import annotations
import enum


class TaskType(enum.Enum):
    CODE_REVIEW = "CODE_REVIEW"
    RAG_VALIDATION = "RAG_VALIDATION"
    ARCHITECTURE_DECISION = "ARCHITECTURE_DECISION"
    GENERAL_CRITIQUE = "GENERAL_CRITIQUE"
    AUTO = "AUTO"


class DefectType(enum.Enum):
    LOGICAL_FALLACY = "LOGICAL_FALLACY"
    FACTUAL_ERROR = "FACTUAL_ERROR"
    MISSING_CONSIDERATION = "MISSING_CONSIDERATION"
    SECURITY_RISK = "SECURITY_RISK"
    PERFORMANCE_ISSUE = "PERFORMANCE_ISSUE"
    UNSUPPORTED_ASSUMPTION = "UNSUPPORTED_ASSUMPTION"
    SCALABILITY_CONCERN = "SCALABILITY_CONCERN"
    COST_INEFFICIENCY = "COST_INEFFICIENCY"
    GENERAL = "GENERAL"


class Severity(enum.Enum):
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"


class FixKind(enum.Enum):
    CONCRETE_FIX = "CONCRETE_FIX"
    VALIDATION_STEP = "VALIDATION_STEP"
    NEED_MORE_DATA = "NEED_MORE_DATA"


class ProviderMode(enum.Enum):
    STABLE = "STABLE"
    BALANCED = "BALANCED"
    DIVERSE = "DIVERSE"


class ConvergenceMode(enum.Enum):
    CRITICAL_CLEARED = "CRITICAL_CLEARED"
    MANUAL = "MANUAL"


class JobStatus(enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    DONE = "DONE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TerminationReason(enum.Enum):
    COMPLETED = "COMPLETED"
    QUORUM_FAILED = "QUORUM_FAILED"
    JUDGE_FAILED = "JUDGE_FAILED"
    COST_BUDGET_EXCEEDED = "COST_BUDGET_EXCEEDED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"


class RoleStatus(enum.Enum):
    SUCCESS = "SUCCESS"
    PARSE_FAILED = "PARSE_FAILED"
    ROLE_FAILED = "ROLE_FAILED"